repos:
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
    -   id: shellcheck
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [markdown]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
