#!/bin/bash
set -eu

if [ "$#" -lt 1 ]; then
    echo "usage: $(basename "${0}") [git-clone-options] <repository>"
    exit 1
fi

url="${@: -1}"
case ${url} in
    *://*/*/*)
        # https://git.sr.ht/~maxmouchet/website
        # host=git.sr.ht, user=~maxmouchet, repo=website
        host=$(echo "${url}" | cut -d "/" -f 3)
        path=$(echo "${url}" | cut -d "/" -f 4-)

        ;;
    *@*:*/*)
        # git@github.com:maxmouchet/HMMBase.jl.git
        # host=github.com, user=maxmouchet, repo=HMMBase.jl.git
        all=$(echo "${url}" | cut -d "@" -f 2)
        host=$(echo "${all}" | cut -d ":" -f 1)
        path=$(echo "${all}" | cut -d ":" -f 2 | cut -d "/" -f 1-)

        ;;
    *)
        echo "Unsupported URL: ${url}"
        exit 1
        ;;
esac

basedir=${CLONE_BASE_DIR:-$HOME/Clones}
path="${path#\~}"
target="${basedir}/${host}/${path%.git}"

git clone "$@" "${target}"

if command -v autojump > /dev/null; then
    autojump --add "${target}"
fi
