#!/bin/bash
set -eu
export CLONE_BASE_DIR=$(mktemp -d)

urls=(
    https://github.com/octocat/Hello-World
    https://git.sr.ht/~sircmpwn/git.sr.ht
    https://gitlab.com/gitlab-org/cells/router
)

dirs=(
    "$CLONE_BASE_DIR/github.com/octocat/Hello-World"
    "$CLONE_BASE_DIR/git.sr.ht/sircmpwn/git.sr.ht"
    "$CLONE_BASE_DIR/gitlab.com/gitlab-org/cells/router"
)

for url in ${urls[@]}; do
    ./clone $url
done

tree -L 3 $CLONE_BASE_DIR

for dir in ${dirs[@]}; do
    if [ ! -d $dir ]; then
        echo "$dir not found"
        exit 1
    fi
done

rm -rf $CLONE_BASE_DIR
